apiVersion: apps/v1
kind: Deployment
metadata:
  name: authen-service
  labels:
    app: authen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authen
  template:
    metadata:
      labels:
        app: authen
    spec:
      containers:
        - name: authen
          image: your-docker-registry/authen-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: authen-secrets
                  key: postgres_dsn
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: authen-secrets
                  key: redis_addr
